version: '3.8'

volumes:
  db-data:

networks:
  cv-network:
    driver: bridge

services:
  # php(api)
  app:
    build:
      context: ./docker/php
    volumes:
      - $BACKEND_DIR:/laravel
    networks:
      - cv-network

  # nginx
  web:
    build:
      context: ./docker/nginx
    ports:
      - $NGINX_PORT:80
    volumes:
      - $BACKEND_DIR:/laravel
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: $NGINX_DIR
    depends_on:
      - app
    networks:
      - cv-network

  # MySQL
  db:
    build:
      context: ./docker/mysql
      args:
        MYSQL_DATABASE: $MYSQL_DATABASE
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD
        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - $DB_PORT:3306
    networks:
      - cv-network

  # node, nuxt(front)
  front:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    command: yarn run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevents overwriting node_modules inside the container
    working_dir: /app
    ports:
      - '$FRONT_PORT:3000'
      - '$STORYBOOK_PORT:6006'
    init: true
    restart: on-failure
    user: "node"
    networks:
      - cv-network

  #phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    depends_on:
      - db
    networks:
      - cv-network
